"""empty message

Revision ID: a97ba624a1bb
Revises: ffdc0a98111c
Create Date: 2023-01-25 08:53:25.894555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97ba624a1bb'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('header', sa.String(length=60), nullable=False),
                    sa.Column('about', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('community_id', sa.Integer(), nullable=True),
                    sa.Column('title', sa.String(length=300), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('edited_by', sa.String(
                        length=50), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['community_id'], ['communities.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('users', sa.Column(
        'is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_table('posts')
    op.drop_table('communities')
    # ### end Alembic commands ###
