"""empty message

Revision ID: 8ecfa6618176
Revises: 2b8ca8eadb17
Create Date: 2023-01-30 06:35:25.713054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ecfa6618176'
down_revision = '2b8ca8eadb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('edited_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'edited_by')
    # ### end Alembic commands ###